name: Deploy infrastructure on LocalStack
on:
  push:
    ignore:
      - 'README. md' branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  terraform:
    name: Deploy infrastructure using Terraform 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
      uses: actions/checkout@v3
      - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      - name: Set up Python 3.10
        id: setup-python
        uses: actions/setup-python@v2 
        with:
          python-version: "3.10"
      - name: Start LocalStack 
        env:
          DNS_ADDRESS: 0
        run: |
          pip install localstack awscli-local[ver1]
          pip install terraform-local docker pull localstack/localstack-pro: latest
        # Start LocalStack in the background
          localstack start -d
          # Wait 30 seconds for the LocalStack container to become ready befor
          echo "Waiting for LocalStack startup……"
          localstack wait -t 15
          echo "Startup complete"
      - name: Deploy on Terraform 
        run:
          cd 02-serverless-api-ecs-apigateway/terraform
          †flocal init
          tflocal apply —auto-approvel
      - name: Check deployed resources run:
        sleep 10
        awslocal apigatewayv2 get-apis
        awslocal cognito-idp list-user-pools —max-results 1
      - name: Send a Slack notification
        if: failure() |I github.event_name != 'pull_request' 
        uses: ravsamhq/notify-slack-action@v2 
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}